### ISSUE TITLE
Reconsider ADR doc location?

### ISSUE THREAD

**Issue by hshaosf** [SFDigitalServices/microservice-py#7]
It became apparent that if we put ADR into this repo, all forked repo will pull in the ADRs as well, which might or might not be desirable.  Discuss?

**Comment by sashax** [comment]
why is that a problem?

**Comment by hshaosf** [comment]
Feels like kinda weird? which might not even be an issue. Just want to get others thoughts on this. 

Example, so when I create an awesome microservice forking off this repo, my awesome-microservice repo will also contain the ADRs, which I am assuming not many will update in their own repo. But feels better there is just one single source of truth for the ADRs, versus copies of it everywhere. If there is an update to the ADR, unless the repo owner does an upstream pull, it won't get updated with new information or findings.

**Comment by hshaosf** [comment]
Also there might ADRs that's specific to the forked repo, which might make things confusing to differentiate which are general microservice decisions and which are decisions for that specific repo. Or maybe a better doc structure will suffice versus generic `adr` folder or maybe coming up with a standard for naming convention for differentiation.

**Comment by sashax** [comment]
Let's try it the way it is and if it becomes a problem we can change it.

**Comment by hshaosf** [comment]
> Let's try it the way it is and if it becomes a problem we can change it.

Sounds good. Closing this unless others have comments.
